# Python Numpy Library


### Python Numpy

#### The python numpy library is used for data science and in ML. It is used because of the following reasons. 

*  Numpy provide efficient Storage 
*  It also provide better ways of handling data for processing 
*  It is fast 
*  It is easy to learn 
*  Numpy uses relatively less memory to store data

In [1]:
import numpy as np

In [2]:
myarr = np.array([[23,43,54,65,76],[2,453,4,745,5]],np.int16)

In [3]:
print(myarr)
myarr

[[ 23  43  54  65  76]
 [  2 453   4 745   5]]


array([[ 23,  43,  54,  65,  76],
       [  2, 453,   4, 745,   5]], dtype=int16)

In [4]:
# Printing the elements of the array by index

print(myarr[1,1])

# Get the number of rows and columns in array
print("The rows and columns in myarray is : ",myarr.shape)

453
The rows and columns in myarray is :  (2, 5)


In [5]:
myarr.dtype

dtype('int16')

In [6]:
# Change the array element by index
print("Printing the data at index before changing : ",myarr[1,2])
myarr[1,2] = 567
print("Printing the data at index before changing : ",myarr[1,2])


Printing the data at index before changing :  4
Printing the data at index before changing :  567


### Array Creation : Conversion from other Python Structutes

In [7]:
listarray = np.array([[1,2,3],[4,5,6],[43,45,56]])

In [8]:
listarray


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [43, 45, 56]])

In [9]:
listarray.dtype


dtype('int32')

In [10]:
print(listarray.size)

9


In [11]:
list1 = np.array({1,2,3,4,5,12,2,1})

In [12]:
zeros = np.zeros((2,5))

In [13]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
zeros.dtype

dtype('float64')

In [15]:
# It will create a array upto given range-1
rng = np.arange(40)

In [16]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [19]:
# It will give a array of equally spaced array in a given range

# lspace = np.linspace(starting,ending,interval)
lspace = np.linspace(1,50,10)

In [20]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [21]:
# Make a 2-D array of defined size and array contains random elements in it
emp = np.empty((4,6))

In [22]:
emp

array([[2.50521045e-292, 1.25990589e-300, 0.00000000e+000,
        2.40157442e-239, 4.41674275e-291, 3.04039619e-316],
       [3.05567394e-311, 0.00000000e+000, 0.00000000e+000,
        1.02744157e-300, 1.38258698e-316, 2.98424756e-309],
       [4.42620148e-297, 2.50521045e-292, 1.98202424e-311,
        4.63927641e-321, 4.66258841e-316, 0.00000000e+000],
       [0.00000000e+000, 8.95520950e-312, 2.10966031e-321,
        1.72390815e-287, 4.47231739e-262, 1.99255405e-311]])

In [23]:
# Create a 1-D Array
emp1 = np.empty((8))

In [24]:
emp1

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 3.04344438e-321, 1.29061142e-306, 0.00000000e+000])

In [26]:
# Create a identity Matrix of NXN
id = np.identity(5)

In [27]:
id

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
id.shape

(5, 5)

## Numpy Axis

In [29]:
arr = [[1,2,3],[4,5,6],[7,8,9]]

In [30]:
arr

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [31]:
x = np.array(arr)

In [32]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
# It will transpose the array
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [34]:
# Flat the 2-D Array
x.flat

In [35]:
for item in x.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [38]:
# get The dimension of the array
print('The dimension of array x is : ',x.ndim)

The dimension of array x is :  2


In [39]:
# Get all element count in the array
x.size

9

In [40]:
# Total bytes consumed by the array
print("Total bytes consumed by the array x is : ",x.nbytes)

Total bytes consumed by the array x is :  36


In [46]:
# Create a 1_D Array
one = np.array([23,343,54,165,5])

In [47]:
one

array([ 23, 343,  54, 165,   5])

In [48]:
# Attribute doesn't require () where as funtion take()

# Print the index of Maximum Element
one.argmax()

1

In [49]:
# Print the minimum element index from the array
one.argmin()

4

In [50]:
# It tell how your index should be to become sorted
one.argsort()

array([4, 0, 2, 3, 1], dtype=int64)

### Mathematical Functions by numpy 

In [51]:
arr1 = np.array([[1,2,3],
                 [32,4,5],
                 [54,65,76]])

In [52]:
arr1

array([[ 1,  2,  3],
       [32,  4,  5],
       [54, 65, 76]])

In [53]:
arr2 = np.array([[12,5,3],
                 [3,4,5],
                 [5,9,74]])

In [54]:
arr2

array([[12,  5,  3],
       [ 3,  4,  5],
       [ 5,  9, 74]])

In [55]:
# Print the sum of two 2-D arrays
arr1+arr2

array([[ 13,   7,   6],
       [ 35,   8,  10],
       [ 59,  74, 150]])

In [56]:
# Print the Product of two 2-D arrays
arr1*arr2

array([[  12,   10,    9],
       [  96,   16,   25],
       [ 270,  585, 5624]])

In [57]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [5.65685425, 2.        , 2.23606798],
       [7.34846923, 8.06225775, 8.71779789]])

#### Print the sum of all the matrix Element

In [58]:
arr2.sum()

120

#### Print the Max of two 2-D arrays

In [59]:
arr2.max()

74

#### Print the Min of two 2-D arrays

In [60]:
arr2.min()

3

In [61]:
# return the count of non zero element from the array
np.count_nonzero(arr2)

9