Creating Nd Arrays


#### Method - 1


In [1]:
# Import Numpy as np

import numpy as np

# Create a 1D array of numbers from 0 to 9
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
arr = [1, 2, 3, 4, 5, 67, 88]
arr

[1, 2, 3, 4, 5, 67, 88]

In [5]:
arr = np.array(arr)
print(arr)
type(arr)

[ 1  2  3  4  5 67 88]


numpy.ndarray

In [8]:
arr2 = np.array([[1, 2, 3, 4, 5, 6], [2, 3, 4, 5, 6, 6]])
arr2

array([[1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6, 6]])

#### Method - 2


In [14]:
# Creates arrays having only ones
arr3 = np.ones((1, 4))
arr3

array([[1., 1., 1., 1.]])

#### Method - 3


In [13]:
# Creates arrays having only zeros
arr3 = np.zeros((2, 4))
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
# Fill

arr2.fill(1)
arr2

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

#### Method - 4


In [15]:
# Create Identity Matrix

arr5 = np.identity(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# Create Array from 5 - 19
# variable = np.arange(start,end,step)
arr = np.arange(5, 16)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])