#### Important Attributes and Properties

In [1]:
import numpy as np


arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr.shape

(9,)

In [5]:
arr2 = np.array([[1,23,45],[43,45,56],[21,45,65],[[1,23,45],[43,45,56],[21,45,65]]])
arr2.shape

(3, 3)

In [9]:
# Get the dimension of the matrix

print(arr2.ndim
,arr.ndim)

2 1


In [11]:
print(arr2.size,arr2.itemsize)

9 4


In [20]:
arr3 = np.array(
    [[[1,2,3,4],
    [1,2,3,4],
    [1,2,3,4]],
    [[1,2,3,4],
    [1,2,3,4],
    [1,2,3,4]]]
)

arr3

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [23]:
arr7 = np.zeros((3,3))

np.fill_diagonal(arr7,6)
print(arr7)
print(arr7.dtype)


[[6. 0. 0.]
 [0. 6. 0.]
 [0. 0. 6.]]
float64


In [24]:
# Convert the datatype of the array
arr7.astype("int64")

array([[6, 0, 0],
       [0, 6, 0],
       [0, 0, 6]], dtype=int64)