### Indexing Slicing and Iteration


In [2]:
import numpy as np

In [8]:
arr = np.arange(25)
print(arr)
print("Reshaped the List by Reshape method")
arr = arr.reshape(5,5)
arr

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
Reshaped the List by Reshape method


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
# Print the Array by Iteration
# Get the Second Row
print(arr[2])

# Get the Particluar Index
print(arr[2][3])

# 2-D array Slicing
print(arr[:2])

# Print Third column
print(arr[:,2])

# Print second and third column
print(arr[:,2:4])

print("Print 12,13 and 17,18 by slicing")
print(arr[2:4,2:4])

[10 11 12 13 14]
13
[[0 1 2 3 4]
 [5 6 7 8 9]]
[ 2  7 12 17 22]
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]
 [22 23]]
Print 12,13 and 17,18 by slicing
[[12 13]
 [17 18]]


In [19]:
# Iteration

for i in arr:
    print(i)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]


In [21]:
for i in np.nditer(arr):
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 