#### Numpy Operations


In [2]:
import numpy as np

In [8]:
arr1 = np.arange(1, 7)
arr2 = np.arange(4, 10)
print(arr1)
print(arr2)

[1 2 3 4 5 6]
[4 5 6 7 8 9]


In [9]:
# Get Element Wise Substraction
arr2 - arr1

array([3, 3, 3, 3, 3, 3])

In [10]:
print(arr2 * arr1)

[ 4 10 18 28 40 54]


In [12]:
print(arr1 * 2)

[ 2  4  6  8 10 12]


In [15]:
arr1 > 3

array([False, False, False,  True,  True,  True])

In [19]:
# Dot Product

arr2 = np.arange(6).reshape(2, 3)
arr3 = np.arange(12).reshape(3, 4)

arr4 = arr2.dot(arr3)
print(arr4)
print(arr4.shape)

[[20 23 26 29]
 [56 68 80 92]]
(2, 4)


In [20]:
# Get the max
print(arr4.max())

92


In [21]:
print(arr4.min())

20


In [24]:
print(arr4)
print("Print the columnwise Minimum")
print(arr4.min(axis=0))

[[20 23 26 29]
 [56 68 80 92]]
[20 23 26 29]


In [27]:
# Print the sum
print(arr4.sum())

# Print the row-wise/column-wise sum
print(arr4.sum(axis = 0))

394
[ 76  91 106 121]
