### Fancy Indexing


In [2]:
import numpy as np

In [5]:
arr = np.arange(24).reshape(6, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
# Print 1,3,5 row Normal Method
  
print(arr[0],arr[2],arr[4])

[0 1 2 3] [ 8  9 10 11] [16 17 18 19]


In [7]:
# Print 1,3,5 row by Fancy Indexing
print(arr[[0,2,4]])

[[ 0  1  2  3]
 [ 8  9 10 11]
 [16 17 18 19]]
