#### Indexing Using boolean arrays

In [1]:
import numpy as np

In [2]:
arr = np.arange(35).reshape(5,7)
arr

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [9]:
print(arr>15)
(arr>15).shape

[[False False False False False False False]
 [False False False False False False False]
 [False False  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]


(5, 7)

In [6]:
arr[arr>15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34])

In [15]:
# Print all the number which are >30 and even
arr[(arr>15) & (arr%2==0)]

array([16, 18, 20, 22, 24, 26, 28, 30, 32, 34])